name: Continuous Delivery

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t oussamazemzami/lol-tracker-frontend:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker Image
      run: docker push oussamazemzami/lol-tracker-frontend:latest

    # Deploy using Portainer API
    - name: Deploy to Portainer
      run: |
        curl -X POST "http://172.104.152.75:9000/api/endpoints/2/docker/containers/create?name=lol-tracker-frontend" \
          -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "Image": "oussamazemzami/lol-tracker-frontend:latest",
                "Env": [],
                "HostConfig": {
                  "RestartPolicy": {
                    "Name": "always"
                  }
                }
              }'
        curl -X POST "http://172.104.152.75:9000/api/endpoints/2/docker/containers/lol-tracker-frontend/start" \
          -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}"
